version: '3.8'

services:
  api_service:
    build:
      context: ./api_service
    ports:
      - "3009:3001"
    env_file:
      - ./api_service/.env
    networks:
      - dingdong

  socket_service:
    build:
      context: ./socket_service
    ports:
      - "3008:3002"
    env_file:
      - ./socket_service/.env
    depends_on:
      - redis
    networks:
      - dingdong

  redis:
    image: redis:7.2-alpine  # Using stable Redis version
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dingdong
    command: redis-server --appendonly yes  # Enable AOF persistence

  api-gateway:
    image: nginx:1.25-alpine  # Using stable Nginx version
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_service
      - socket_service
    networks:
      - dingdong

networks:
  dingdong:
    driver: bridge
